### ISSUE TITLE
Country Ticker

### ISSUE THREAD

**Issue by AWCrypt** [papacarp/pooltool.io#2]
It would be great to have a country code pools can select when claiming their pools so we can all see which countries are leading in block creation and we can also start having inter country competitions :)

**Comment by papacarp** [comment]
i just got another request for this.

**Comment by JustStaking** [comment]
This would be a useful feature.
From this we can also heat-map hotspots and deadzones in terms of number of blocks created. 
Which might reveal unexpected biases.

**Comment by papacarp** [comment]
I was thinking about this today that it might be interesting to do this as more of a general attributes thing.  We could collect attributes of all kinds for each of the pools that we could then plot/parse, etc  Things that come to mind:

*Geography*
- Country
- Continent
- GPS Lat Lng

*Server infrastructure*
- Server Farm (AWS, Google, Digital ocean)
- CPU Count
- Operating System
- Memory Allocated
- Bandwidth to Internet

*Node Configuration*
- Max connections
- Public or private IP

*Other*
- Private Pool / Public Pool
- ??

Please let let me know  what types of data operators might be willing to share and find useful for comparisons.

**Comment by JustStaking** [comment]
Your noted attributes would be really handy to gather and review but my concern with too much specific data is that it will be used against us by bad actors, ie anti-Cardano folks and hackers in general.
Too much info makes their life a little easier.
I think pool country is ok to show publicly, but any other data should be almost anonymous with only aggregated results being shown publicly ie total number of each different operating system (but no version info, otherwise known vulns can be attempted/exploited).

**Comment by papacarp** [comment]
country affiliation is now in!  Once I see a few of you in there I'll add a page to summarize stats by country :)
