### ISSUE TITLE
Feature Request: 6 Decimals for Stake Rewards Column

### ISSUE THREAD

**Issue by WoodDesk** [papacarp/pooltool.io#88]
In the rewards tracking page for any given address, it would be very nice to be able to see the exact amount of rewards down to the last lovelace.  This column in particular: **Stake Rewards (₳)**. 

A toggle to switch between the default 3 decimal view to a 6 decimal view, or defaulting to the 6 decimal view should a toggle be overly complicated.

This would be greatly appreciated.  Thanks for all the amazing work.

**Comment by papacarp** [comment]
due to how we calculate rewards rather than pull them straight from the node, there are a few lovelace differences on some accounts. because of that we haven't wanted to get it down to the exact lovelace.  However, we went ahead and added a "copy" button to some of the columns on that page that should help.

If we get funded in the catalyst project we are planning to upgrade that section of pooltool significanly and will get all the precision directly out of the node.
